package hr.sdo.bootcamp.model.views;

import java.math.BigDecimal;

import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 07 10:23:08 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SdoEmployeesViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_EMPLOYEES = 0;
    public static final int ENTITY_DEPARTMENTS = 1;
    public static final int ENTITY_JOBS = 2;
    public static final int ENTITY_MANAGERS = 3;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CommissionPct {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getCommissionPct();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setCommissionPct((BigDecimal)value);
            }
        }
        ,
        DepartmentId {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getDepartmentId();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setDepartmentId((Integer)value);
            }
        }
        ,
        Email {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getEmail();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        EmployeeId {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getEmployeeId();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setEmployeeId((Integer)value);
            }
        }
        ,
        FirstName {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getFirstName();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        HireDate {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getHireDate();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setHireDate((Timestamp)value);
            }
        }
        ,
        JobId {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getJobId();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setJobId((String)value);
            }
        }
        ,
        LastName {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getLastName();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        ManagerId {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getManagerId();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setManagerId((Integer)value);
            }
        }
        ,
        PhoneNumber {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getPhoneNumber();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setPhoneNumber((String)value);
            }
        }
        ,
        Salary {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getSalary();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setSalary((BigDecimal)value);
            }
        }
        ,
        DepartmentName {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getDepartmentName();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setDepartmentName((String)value);
            }
        }
        ,
        DepartmentId1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getDepartmentId1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setDepartmentId1((Integer)value);
            }
        }
        ,
        JobTitle {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getJobTitle();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setJobTitle((String)value);
            }
        }
        ,
        JobId1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getJobId1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setJobId1((String)value);
            }
        }
        ,
        FirstName1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getFirstName1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setFirstName1((String)value);
            }
        }
        ,
        LastName1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getLastName1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setLastName1((String)value);
            }
        }
        ,
        Email1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getEmail1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setEmail1((String)value);
            }
        }
        ,
        EmployeeId1 {
            public Object get(SdoEmployeesViewRowImpl obj) {
                return obj.getEmployeeId1();
            }

            public void put(SdoEmployeesViewRowImpl obj, Object value) {
                obj.setEmployeeId1((Integer)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SdoEmployeesViewRowImpl object);

        public abstract void put(SdoEmployeesViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int HIREDATE = AttributesEnum.HireDate.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int DEPARTMENTID1 = AttributesEnum.DepartmentId1.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int JOBID1 = AttributesEnum.JobId1.index();
    public static final int FIRSTNAME1 = AttributesEnum.FirstName1.index();
    public static final int LASTNAME1 = AttributesEnum.LastName1.index();
    public static final int EMAIL1 = AttributesEnum.Email1.index();
    public static final int EMPLOYEEID1 = AttributesEnum.EmployeeId1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SdoEmployeesViewRowImpl() {
    }

    /**
     * Gets Employees entity object.
     * @return the Employees
     */
    public EntityImpl getEmployees() {
        return (EntityImpl)getEntity(ENTITY_EMPLOYEES);
    }

    /**
     * Gets Departments entity object.
     * @return the Departments
     */
    public EntityImpl getDepartments() {
        return (EntityImpl)getEntity(ENTITY_DEPARTMENTS);
    }

    /**
     * Gets Jobs entity object.
     * @return the Jobs
     */
    public EntityImpl getJobs() {
        return (EntityImpl)getEntity(ENTITY_JOBS);
    }

    /**
     * Gets Managers entity object.
     * @return the Managers
     */
    public EntityImpl getManagers() {
        return (EntityImpl)getEntity(ENTITY_MANAGERS);
    }

    /**
     * Gets the attribute value for COMMISSION_PCT using the alias name CommissionPct.
     * @return the COMMISSION_PCT
     */
    public BigDecimal getCommissionPct() {
        return (BigDecimal) getAttributeInternal(COMMISSIONPCT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISSION_PCT using the alias name CommissionPct.
     * @param value value to set the COMMISSION_PCT
     */
    public void setCommissionPct(BigDecimal value) {
        setAttributeInternal(COMMISSIONPCT, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public Integer getEmployeeId() {
        return (Integer) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(Integer value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for HIRE_DATE using the alias name HireDate.
     * @return the HIRE_DATE
     */
    public Timestamp getHireDate() {
        return (Timestamp) getAttributeInternal(HIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for HIRE_DATE using the alias name HireDate.
     * @param value value to set the HIRE_DATE
     */
    public void setHireDate(Timestamp value) {
        setAttributeInternal(HIREDATE, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public String getJobId() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(String value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(Integer value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @return the PHONE_NUMBER
     */
    public String getPhoneNumber() {
        return (String) getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @param value value to set the PHONE_NUMBER
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for SALARY using the alias name Salary.
     * @return the SALARY
     */
    public BigDecimal getSalary() {
        return (BigDecimal) getAttributeInternal(SALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for SALARY using the alias name Salary.
     * @param value value to set the SALARY
     */
    public void setSalary(BigDecimal value) {
        setAttributeInternal(SALARY, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId1.
     * @return the DEPARTMENT_ID
     */
    public Integer getDepartmentId1() {
        return (Integer) getAttributeInternal(DEPARTMENTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId1.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId1(Integer value) {
        setAttributeInternal(DEPARTMENTID1, value);
    }

    /**
     * Gets the attribute value for JOB_TITLE using the alias name JobTitle.
     * @return the JOB_TITLE
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITLE using the alias name JobTitle.
     * @param value value to set the JOB_TITLE
     */
    public void setJobTitle(String value) {
        setAttributeInternal(JOBTITLE, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId1.
     * @return the JOB_ID
     */
    public String getJobId1() {
        return (String) getAttributeInternal(JOBID1);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId1.
     * @param value value to set the JOB_ID
     */
    public void setJobId1(String value) {
        setAttributeInternal(JOBID1, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName1.
     * @return the FIRST_NAME
     */
    public String getFirstName1() {
        return (String) getAttributeInternal(FIRSTNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName1.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName1(String value) {
        setAttributeInternal(FIRSTNAME1, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName1.
     * @return the LAST_NAME
     */
    public String getLastName1() {
        return (String) getAttributeInternal(LASTNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName1.
     * @param value value to set the LAST_NAME
     */
    public void setLastName1(String value) {
        setAttributeInternal(LASTNAME1, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email1.
     * @return the EMAIL
     */
    public String getEmail1() {
        return (String) getAttributeInternal(EMAIL1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email1.
     * @param value value to set the EMAIL
     */
    public void setEmail1(String value) {
        setAttributeInternal(EMAIL1, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId1.
     * @return the EMPLOYEE_ID
     */
    public Integer getEmployeeId1() {
        return (Integer) getAttributeInternal(EMPLOYEEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId1.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId1(Integer value) {
        setAttributeInternal(EMPLOYEEID1, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
